#!/usr/bin/env bash
# First-run setup for OpenClaw / Docker: persistent mcporter + AgentPay configs.
# Usage:
#   AGENTPAY_BACKEND_URL=http://host:3000 AGENTPAY_AGENT_ID=agent_123 \
#     ./scripts/openclaw-install.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MCP_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

OPENCLAW_HOME="${OPENCLAW_HOME:-/home/node/.openclaw}"
AGENTPAY_MCP_ROOT="${AGENTPAY_MCP_ROOT:-$OPENCLAW_HOME/agentpay-mcp}"
MCPORTER_CONFIG="${MCPORTER_CONFIG:-$OPENCLAW_HOME/mcporter/mcporter.json}"
MCPORTER_PREFIX="${MCPORTER_PREFIX:-$OPENCLAW_HOME/tools/mcporter}"
AGENTPAY_BACKEND_URL="${AGENTPAY_BACKEND_URL:-http://206.189.229.113:3000}"
AGENTPAY_AGENT_ID="${AGENTPAY_AGENT_ID:-agent_123}"
AGENTPAY_API_KEY="${AGENTPAY_API_KEY:-}"

echo "[openclaw-install] OPENCLAW_HOME=$OPENCLAW_HOME"
echo "[openclaw-install] AGENTPAY_MCP_ROOT=$AGENTPAY_MCP_ROOT"
echo "[openclaw-install] MCPORTER_CONFIG=$MCPORTER_CONFIG"

mkdir -p "$(dirname "$MCPORTER_CONFIG")" "$MCPORTER_PREFIX" "$OPENCLAW_HOME"

MCP_ROOT_ABS="$(cd "$MCP_ROOT" && pwd)"
mkdir -p "$AGENTPAY_MCP_ROOT"
AGENTPAY_MCP_ROOT_ABS="$(cd "$AGENTPAY_MCP_ROOT" && pwd)"

# Copy to persistent path when install runs from a different directory (e.g. CI checkout → volume)
if [[ "$MCP_ROOT_ABS" != "$AGENTPAY_MCP_ROOT_ABS" ]]; then
  echo "[openclaw-install] Copying MCP package to $AGENTPAY_MCP_ROOT_ABS"
  rsync -a --delete \
    --exclude node_modules \
    --exclude build \
    "$MCP_ROOT_ABS/" "$AGENTPAY_MCP_ROOT_ABS/" \
    || cp -r "$MCP_ROOT_ABS/." "$AGENTPAY_MCP_ROOT_ABS/"
fi

cd "$AGENTPAY_MCP_ROOT_ABS"
if [[ -f package.json ]]; then
  npm install --omit=dev 2>/dev/null || npm install
  npm run build
fi

# mcporter → persistent prefix (survives container restart; do not rely on global npm)
echo "[openclaw-install] Installing mcporter to $MCPORTER_PREFIX"
npm install --prefix "$MCPORTER_PREFIX" mcporter@latest

# AgentPay CLI config (~/.agentpay/config.json — on persistent $HOME)
export AGENTPAY_BACKEND_URL AGENTPAY_AGENT_ID AGENTPAY_API_KEY
node "$AGENTPAY_MCP_ROOT/build/index.js" init \
  --backend-url "$AGENTPAY_BACKEND_URL" \
  --agent-id "$AGENTPAY_AGENT_ID" \
  ${AGENTPAY_API_KEY:+--api-key "$AGENTPAY_API_KEY"}

# mcporter MCP server entry
TEMPLATE="$AGENTPAY_MCP_ROOT/config/mcporter.openclaw.json"
if [[ ! -f "$TEMPLATE" ]]; then
  TEMPLATE="$MCP_ROOT/config/mcporter.openclaw.json"
fi

mkdir -p "$(dirname "$MCPORTER_CONFIG")"
sed \
  -e "s|__AGENTPAY_MCP_ROOT__|$AGENTPAY_MCP_ROOT|g" \
  -e "s|__AGENTPAY_BACKEND_URL__|$AGENTPAY_BACKEND_URL|g" \
  "$TEMPLATE" > "$MCPORTER_CONFIG"

ENV_FILE="$AGENTPAY_MCP_ROOT/openclaw.env"
cat > "$ENV_FILE" <<EOF
# Generated by openclaw-install.sh — source in shell profile
export OPENCLAW_HOME="$OPENCLAW_HOME"
export AGENTPAY_MCP_ROOT="$AGENTPAY_MCP_ROOT"
export MCPORTER_CONFIG="$MCPORTER_CONFIG"
export MCPORTER_PREFIX="$MCPORTER_PREFIX"
export AGENTPAY_BACKEND_URL="$AGENTPAY_BACKEND_URL"
export AGENTPAY_AGENT_ID="$AGENTPAY_AGENT_ID"
export PATH="\$MCPORTER_PREFIX/node_modules/.bin:\$PATH"
EOF

echo ""
echo "[openclaw-install] Done."
echo "  AgentPay config:  \$(node -e \"console.log(require('os').homedir()+'/.agentpay/config.json')\")"
echo "  mcporter config:  $MCPORTER_CONFIG"
echo "  mcporter binary:  $MCPORTER_PREFIX/node_modules/.bin/mcporter"
echo "  Env bootstrap:    source $ENV_FILE"
echo ""
echo "Add to OpenClaw workspace (persistent): $OPENCLAW_HOME/workspace"
echo "Install skill from: $AGENTPAY_MCP_ROOT/SKILL.md"
